### ISSUE TITLE
malloc.h not found after `make` command

### ISSUE THREAD

**Issue by Tim-at-AST** [kevinboone/epub2txt2#1]
I'm on mac OSX 10.13.1, MacBook Pro (15-inch, Late 2016)

When I tried to `make` I got a compilation error `malloc.h not found`.

After googling, I solved this by:
1. `touch malloc.h`
2. replace text in all *.c files 
`#include <malloc.h>` to `#include "malloc.h" `

Whilst this may not be the best solution, it seems to work, and I have converted a few sample epubs without any problems.

**Comment by jove4015** [comment]
I just ran into the same thing.  Apparently on Mac they prefer not to use malloc.h but instead stdlib.h.  I made a pull request for it.

**Comment by kevinboone** [comment]
Thanks for the fix for this, which I have merged. I am aware of this little foibles with the Mac gcc, but I don't have a Mac system to test with, so they often get past me.
