### ISSUE TITLE
Packaged in Fedora copr

### ISSUE THREAD

**Issue by boydkelly** [kevinboone/epub2txt2#14]
Hi,
I have been using your awesome utility and packaged it up for Fedora/RedHat/CentOs/Suse in a Fedora copr repostiory.

https://copr.fedorainfracloud.org/coprs/boydkelly/epub2txt2/

Cheers!

**Comment by kevinboone** [comment]
Thank you. Is there any further work for me to do here?

**Comment by kevinboone** [comment]
Since there doesn't seem to be any additional work for me to do, I'm closing this now. Thank you for the contribution.
