### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by uncomfyhalomacro** [kevinboone/epub2txt2#19]
I have planned to package this to openSUSE but it seems like I do not see a LICENSE file.

**Comment by uncomfyhalomacro** [comment]
Sorry i accidentally closed it

**Comment by kevinboone** [comment]
Hi. Does it specifically have to be called "LICENSE" (with that case and spelling?) I'm not familiar with these conventions.

**Comment by uncomfyhalomacro** [comment]
> Hi. Does it specifically have to be called "LICENSE" (with that case and spelling?) I'm not familiar with these conventions.

Hello again. someone in openSUSE told me I can just copy the license text in the readme. btw can i clarify what gpl3 license this is? is it gpl3-only, gpl3-or-later? just to be sure.

**Comment by kevinboone** [comment]
I added a LICENSE file, which is just a copy of the boilerplate GPL 3.0. I hope that helps. If you're packaging this utility, please bear in mind that it has a dependency on the "unzip" utility.

**Comment by uncomfyhalomacro** [comment]
thanks im closing this then :D
