### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by natrys** [kevinboone/epub2txt2#23]
Hi, we were planning to bump this package in Void Linux repository to latest release. But I notice that there are two newer bugfix commits since then, not covered in last release. Do you have plans to release a new version soon? If so we could wait before bumping, thanks.

**Comment by kevinboone** [comment]
Sorry, I kind-of lost track of what significant changes I had made since 2.05. My bad. I have just pushed a 2.06 release which should contain all changes, including the trivial documentation fixes. I hope this helps.

**Comment by natrys** [comment]
It helped, thanks a lot.
