### ISSUE TITLE
mac 2-2.08 make install error

### ISSUE THREAD

**Issue by mrfragger** [kevinboone/epub2txt2#33]
make
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//convertutf.deps -c -o build//convertutf.o src//convertutf.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//epub2txt.deps -c -o build//epub2txt.o src//epub2txt.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//list.deps -c -o build//list.o src//list.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//log.deps -c -o build//log.o src//log.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//main.deps -c -o build//main.o src//main.c 
src//main.c:23:29: warning: omitting the parameter name in a function definition is a C2x extension [-Wc2x-extensions]
static void sig_handler (int)
                            ^
1 warning generated.
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//string.deps -c -o build//string.o src//string.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//sxmlc.deps -c -o build//sxmlc.o src//sxmlc.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//sxmlsearch.deps -c -o build//sxmlsearch.o src//sxmlsearch.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//util.deps -c -o build//util.o src//util.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//wrap.deps -c -o build//wrap.o src//wrap.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//wstring.deps -c -o build//wstring.o src//wstring.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.08\" -DAPPNAME=\"epub2txt\" -MD -MF build//xhtml.deps -c -o build//xhtml.o src//xhtml.c 
gcc -o epub2txt  -s  build//convertutf.o build//epub2txt.o build//list.o build//log.o build//main.o build//string.o build//sxmlc.o build//sxmlsearch.o build//util.o build//wrap.o build//wstring.o build//xhtml.o 
ld: warning: -s is obsolete

sudo make install
Password:
install -D -m 755 epub2txt //usr//bin/epub2txt
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64

this is on mac OS 14.5 Sonoma
is there a way I can exclude the -D option perhaps.  I only usually build whisper.cpp with make -j and no issues.
yeah just tried make clean then make -j and got

src//main.c:23:29: warning: omitting the parameter name in a function definition is a C2x extension [-Wc2x-extensions]
static void sig_handler (int)

**Comment by kevinboone** [comment]
I'm a little confused -- which version of epub2txt2 are you building? The latest version has:

    static void sig_handler (int signo)

so I'm not sure where your compiler warning comes from.

I'm not at all familiar with MacOS. Does it's version of 'install' not support '-D'? This switch may be needed in some cases, particularly when installing in an empty directory (for building an OS package, for example). Is there documentation for the Mac version on 'install'? 

Also, in the GNU version of 'make', '-j' means 'create an unlimited number of jobs'. I'm not sure how that would be relevant here. Perhaps the Mac version is different?

**Comment by mrfragger** [comment]
ok this time download zip from code so 2.10 but still errors.  I compared makefile with whisper.cpp and I got a headache just from glancing at that code...way over my brain.

 make      
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.10\" -DAPPNAME=\"epub2txt2\" -MD -MF build//convertutf.deps -c -o build//convertutf.o src//convertutf.c 
gcc -Wall -Wno-unused-result -O3  -DVERSION=\"2.10\" -DAPPNAME=\"epub2txt2\" -MD -MF build//epub2txt.deps -c -o build//epub2txt.o src//epub2txt.c 
src//epub2txt.c:82:15: error: call to undeclared library function 'strdup' with type 'char *(const char *)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  char *ret = strdup (string_cstr (out));
              ^
src//epub2txt.c:82:15: note: include the header <string.h> or explicitly provide a declaration for 'strdup'
src//epub2txt.c:103:5: error: call to undeclared function 'asprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    asprintf (&s, "%s: %s", key, ss);
    ^
src//epub2txt.c:230:7: error: call to undeclared function 'asprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      asprintf (error, "Can't parse OPF XML");
      ^
src//epub2txt.c:284:2: error: call to undeclared function 'asprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        asprintf (error, "File %s has no manifest", opf);
        ^
src//epub2txt.c:343:7: error: call to undeclared function 'asprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      asprintf (error, "Can't parse OPF XML");
      ^
src//epub2txt.c:407:9: error: call to undeclared function 'asprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        asprintf (error, "container.xml does not specify a root file");
        ^
src//epub2txt.c:412:7: error: call to undeclared function 'asprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      asprintf (error, "Can't parse OPF XML");
      ^
src//epub2txt.c:455:5: error: call to undeclared function 'asprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    asprintf (&tempdir, "%s/epub2txt%d", tempbase, getpid()); 
    ^
src//epub2txt.c:571:5: error: call to undeclared function 'asprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    asprintf (error, "File not found: %s", file);

anyway it's all good...Someday look into Mac perhaps...I'm not a fan myself..much prefer Linux.  Thanks for your efforts.

btw this is what I do after I get chapters put into their own epubs

find "$PWD" -type f -name "*.epub" -exec epub2txt -f {} \; ; find "$PWD" -type f -name "*.txt" -exec mv {} . \; ; for f in *.txt ; do n=`echo $f | sed 's/[^0-9]*//g'` ; p=`printf "%03d" $n`; new=`echo $f | sed "s/${n}/${p}/"`; mv "$f" "$new"; done

I can't really copy the code cuz of the accent marks so will post image
<img width="381" alt="image" src="https://github.com/user-attachments/assets/be23c263-fabb-42bb-8311-bb2ac2dba28d">
