### ISSUE TITLE
Compiling and running on macOS - possibly to add to the README

### ISSUE THREAD

**Issue by axmonti** [kevinboone/epub2txt2#34]
Great utility - compiled and ran perfectly on Cygwin, but when I tried it on macOS...not quite as successful initially, but have it running now. Here are some things for Mac users you may want to add to the README for guidance.

**Compiling**
There are a few libraries that will be marked as "undeclared library function". Editing the Makefile and adding a parameter to EXTRA_CFLAGS as such solves the compilation issue:

`EXTRA_CFLAGS ?= -D_DARWIN_C_SOURCE`

**Deploying**
`sudo make install`  won't work as-is on macOS; it's likely best to ensure that two directories exist prior to running `make install`

```
/usr/local/bin
/usr/local/share/man/man1
```

`/usr/local` will likely exist. If the other subdirectories don't exist, create them with `sudo`. Then modify the `Makefile`

```
PREFIX  := usr/local
BINDIR  := bin
MANDIR  := share/man
```

...

```
install:
	install -D -m $(APPNAME) $(DESTDIR)/$(PREFIX)/$(BINDIR)
	install -D -m man1/epub2txt.1 $(DESTDIR)/$(PREFIX)/$(MANDIR)/man1/epub2txt.1
```

and `sudo make install` will work. `/usr/local` paths for binaries and man pages are by default in the system path.

**Running**
Each time I ran the utility, I ended up with an odd error:

`Bad OPF rootfile path`

To debug, I created an Xcode command-line project and imported the source, set compile parameters, and so on, eventually stepping through the code to find the source of the error. It was the `is_subpath` routine, but only due to the `realpath` routine in the callee.

Unfortunately, the default temporary [directory](https://github.com/sindresorhus/temp-write/issues/8) on macOS is (for historical reasons) a symbolic link. `/tmp` actually points to `/private/tmp` and if the code doesn't see an environment variable called `TMP` or `TEMP`, then it sets `TMP=/tmp`, which (unfortunately) still points to `/private/tmp` which means that when the `tmp` directory path is compared the to the `opf` directory, since the `opf tmp` directory was processed through `realpath`, it will have the `/private` prefix, while the `tempfile` path will not.  This causes the `is_subpath` to fail since the paths will differ here (`!strncmp (root, path, root_len`). The result is the OPF file path error. 

Two potential solutions:
1. Set a temporary directory environment variable on the same line as executing the command, ensuring it doesn't point to `/tmp` e.g.,

`TMP=/Volumes/NEXT/temp epub2txt PrincessOfMars-EPUB2.epub`

This will set the `TMP` variable while the application is in scope and automatically remove it when the program exits. Of course, the full path passed for `TMP` needs to be created before running the application.

Or

2.  Run the `tempbase` directory variable through `realpath` as well, just before the debug line in `epub2txt.c`:

Before the line: 
`log_debug ("tempbase is: %s", tempbase);`

Add: 
`tempbase = realpath (tempbase, NULL);`

This will add `/private` to the `tempbase` path (if required/encountered) and allow the `is_subpath` to work as intended.

After saving the change, run `make` and `sudo make install`. With this solution, there's no need to set or pass a `TMP` directory. The system's underlying `TMP` directory will work invisibly. 

I've read that the author doesn't have a Mac to test this on, but I hope this helps macOS users.

**Comment by kevinboone** [comment]
Thanks for this work. Perhaps these instructions should be in a separate file called 'README.MACOS.md' or something like that? If you committed that change you'd get credit as a contributor, for what little that's worth ;) Up to you, though -- it's no bother for me to do it.

**Comment by axmonti** [comment]
Sounds good; I was waffling between opening an issue and just creating a mac-based "README"; chose the issue route in case you wanted to update the current README (or change the Makefile and/or code). I'm happy to create the a README.MACOS.md and commit - appreciate you providing that option! Will do that shortly.

**Comment by kevinboone** [comment]
Thank you. I have merged your additional file.
