### ISSUE TITLE
Fd leak when opening htmls

### ISSUE THREAD

**Issue by gumblex** [kevinboone/epub2txt2#4]
In file https://github.com/kevinboone/epub2txt2/blob/master/src/wstring.c#L83 , there is no close(). When the epub has many htmls, there will be an error "Too many open files".

**Comment by kevinboone** [comment]
You're absolutely right. Oops :/ I guess I never tested with an EPUB that had enough embedded files to expose this defect. I have commit what I think is the appropriate fix -- feel free to test and let me know if there are still problems.

**Comment by gumblex** [comment]
Seems ok.
