### ISSUE TITLE
With Upgrades - Upgrade Version Number

### ISSUE THREAD

**Issue by teamcoltra** [kevinboone/epub2txt2#6]
Per my other bug, I was checking to see if my version was up-to-date and realized I couldn't. I had compiled the new version, but when I ran -v there was no difference so I realized that there was the addition of --help so I noticed I now have the calibre flag (so it worked).

If you could update the version in --version / -v and here on the site so updates can be tracked that would be great.

**Comment by kevinboone** [comment]
Bumped version to 2.01. I will go to 2.1 and create a new release point when I've finished the current bunch of bug fixes.
